---
- hosts: all
  become: true
  tasks:

  - name: Update Ubuntu Package Cache
    apt:
      update_cache: yes
      state: present

- hosts: all
  become: true
  roles:
    - NTP
    - OpenStack_packages
    - SQL_Database
    - Message_Queue
    - Memcached
    - Etcd

