
- name: Install database packages
  apt:
    name:
      - mariadb-server
      - python3-pymysql
    state: present

- name: Create the /etc/mysql/mariadb.conf.d/99-openstack.cnf file
  file:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    state: touch
    owner: root
    group: root
    mode: 0777

- name: Edit the /etc/mysql/mariadb.conf.d/99-openstack.cnf file
  blockinfile:
    path: /etc/mysql/mariadb.conf.d/99-openstack.cnf
    block: |
      [mysqld]
      bind-address = 10.0.0.11

      default-storage-engine = innodb
      innodb_file_per_table = on
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8

- name: Restart database service
  service:
    name: mariadb
    state: restarted
    enabled: true
